"""UploadedImage.face_data blob

Revision ID: d8158696d864
Revises: f824b44523f1
Create Date: 2018-03-17 13:23:14.290000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8158696d864'
down_revision = 'f824b44523f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_image', sa.Column('face_data', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("uploaded_image") as batch_op:
        batch_op.drop_column('face_data')
