"""UploadedImage model

Revision ID: f824b44523f1
Revises: a1daa35662bc
Create Date: 2018-03-16 13:15:56.835423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f824b44523f1'
down_revision = 'a1daa35662bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.VARCHAR(length=64), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_image')
    # ### end Alembic commands ###
